#!/usr/bin/expect

# Disable output to stdout (terminal)
log_user 0

# Save all output (send/expect) to a file
log_file "./gemini_session_log/gemini_session.log"

set timeout -1

spawn gemini -y

# To be moved to python logic so that we do not have any hardcoded logic there
interact {
    -o -re "(?i)keep trying" {
        # Log to file only, not stdout
        send_log "\n*** Auto-Reply: Saw 'keep trying', sending 1... ***\n"
        
        send "1\r"
        sleep 0.5
    }
}
